/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectopichardo;

import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oem
 */
public class HacerVenta extends javax.swing.JFrame {

    /**
     * Creates new form HacerVenta
     */
    public HacerVenta() {
        initComponents();

        // Limpiar los Items del ComboBox
        jComboBox1.removeAllItems();

        // Llenar ComboBox con libros disponibles
        for (LibroV libro : ProyectoPichardo.getLibrosv()) {
            jComboBox1.addItem(libro.titulo);
        }
// Inicializar ComboBox de cupones
        jComboBox2.removeAllItems();
        jComboBox2.addItem("Sin cupón"); // Agrega esta opción predeterminada
        for (Cupon c : ProyectoPichardo.getCupones()) {
            jComboBox2.addItem("Código: " + c.codigo + " Valor: " + c.valor + " Tipo: " + c.tipo);
        }

        // Configurar columnas del JTable
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Título");
        modelo.addColumn("Precio");
        modelo.addColumn("Cantidad"); // La cantidad siempre será 1 cada vez que selecciones
        jTable1.setModel(modelo);

        // Escuchar selección del ComboBox
        jComboBox1.addActionListener(e -> agregarLibroAVenta());
    }

    public javax.swing.JComboBox<String> getComboBoxLibros() {
        return jComboBox1;
    }

    public void actualizarComboBox() {
        jComboBox1.removeAllItems();
        for (LibroV libro : ProyectoPichardo.getLibrosv()) {
            jComboBox1.addItem(libro.titulo);
        }
    }

    private void agregarLibroAVenta() {
        String tituloSeleccionado = (String) jComboBox1.getSelectedItem();

        if (tituloSeleccionado == null) {
            return;
        }

        for (LibroV libro : ProyectoPichardo.getLibrosv()) {
            if (libro.titulo.equalsIgnoreCase(tituloSeleccionado)) {
                if (libro.stock > 0) {
                    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
                    modelo.addRow(new Object[]{libro.titulo, libro.precio, 1});
                    libro.stock--;

                    JOptionPane.showMessageDialog(this, "Quedan " + libro.stock + " unidades de " + libro.titulo);

                    if (libro.stock == 0) {
                        JOptionPane.showMessageDialog(this, "Ya no hay stock de " + libro.titulo);
                    }

                    // También reducir en el inventario
                    for (Libros lib : ProyectoPichardo.getLibros()) {
                        if (lib.titulo.equalsIgnoreCase(libro.titulo)) {
                            lib.stock--;
                            break;
                        }
                    }

                    break;
                } else {
                    JOptionPane.showMessageDialog(this, "Ya no hay stock de " + libro.titulo);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Escoger Libros");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hacer venta");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoger Cupon");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if (jTable1.getRowCount() == 0) {
        JOptionPane.showMessageDialog(this, "No hay libros en la venta.");
        return;
    }

    String nombreCliente = JOptionPane.showInputDialog(this, "Ingrese el nombre del cliente:");
    String nitCliente = JOptionPane.showInputDialog(this, "Ingrese el NIT del cliente:");
    String direccionCliente = JOptionPane.showInputDialog(this, "Ingrese la dirección del cliente:");

    if (nombreCliente == null || nitCliente == null || direccionCliente == null) {
        JOptionPane.showMessageDialog(this, "Venta cancelada.");
        return;
    }

    double totalConIVA = 0;
    for (int i = 0; i < jTable1.getRowCount(); i++) {
        double precio = (double) jTable1.getValueAt(i, 1);
        totalConIVA += precio;
    }

    // Obtener cupón seleccionado
    String seleccion = (String) jComboBox2.getSelectedItem();
    double descuento = 0;
    String detalleCupon = "Sin cupón";

    if (seleccion != null && !seleccion.equals("Sin cupón")) {
        for (Cupon c : ProyectoPichardo.getCupones()) {
            String etiqueta = "Código: " + c.codigo + " Valor: " + c.valor + " Tipo: " + c.tipo;
            if (etiqueta.equals(seleccion)) {
                detalleCupon = etiqueta;
                if (c.tipo.equalsIgnoreCase("Porcentual")) {
                    double porcentaje = Double.parseDouble(c.valor);
                    descuento = totalConIVA * (porcentaje / 100);
                } else if (c.tipo.equalsIgnoreCase("Monto fijo")) {
                    descuento = Double.parseDouble(c.valor);
                }
                break;
            }
        }
    }

    totalConIVA -= descuento;
    totalConIVA = Math.round(totalConIVA * 100.0) / 100.0;
    double totalSinIVA = Math.round((totalConIVA / 1.12) * 100.0) / 100.0;

    String nombreVendedor = ProyectoPichardo.getUsuarioActual().getNombre();
    Calendar fecha = Calendar.getInstance();

    Venta nueva = new Venta();
    nueva.nombre = nombreCliente;
    nueva.nit = nitCliente;
    nueva.direccion = direccionCliente;
    nueva.total = totalConIVA;
    nueva.vendedor = nombreVendedor;
    nueva.fecha = fecha;

    ProyectoPichardo.getVentas().add(nueva);

    String factura = "Factura\n\n" +
        "Nombre: " + nombreCliente + "\n" +
        "NIT: " + nitCliente + "\n" +
        "Dirección: " + direccionCliente + "\n" +
        "Vendedor: " + nombreVendedor + "\n" +
        "Fecha: " + fecha.getTime().toString() + "\n" +
        "Total sin IVA: Q" + totalSinIVA + "\n" +
        "Cupón aplicado: " + detalleCupon + "\n" +
        "Descuento aplicado: Q" + Math.round(descuento * 100.0) / 100.0 + "\n" +
        "Total con IVA: Q" + totalConIVA;

    JOptionPane.showMessageDialog(this, factura);

    // Limpiar tabla
    DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
    modelo.setRowCount(0);

    // Restaurar selección de cupón
    jComboBox2.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
